# Generated by Django 3.2.11 on 2022-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uername',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='username'),
        ),
    ]
